{
 "title": "Métricas",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 5 Ganadores",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT nombre, victorias\r\nFROM jugador\r\nORDER BY victorias DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Latencia de la API",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(latencia_api_sum[1m]) / rate(latencia_api_count[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conteo de puntuaciones altas (6)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "puntuaciones_altas_total\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jugadores Registrados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jugadores_registrados_totales_total\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partidas Jugadas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "partidas_creadas_totales_total\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de tiradas realizadas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tiradas_totales_total\r\n", "legendFormat": "__auto" }
   ]
  }
 ]
}